stages:
 - template: azure/stages.yml@templates
   parameters:
     minrust: false

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      ref: refs/heads/v0.2
      endpoint: Geobert
