[package]
name = "emile"
version = "0.1.0"
authors = ["Geobert Quach <geobert@protonmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.3"
anyhow = "1.0.18"
toml = "0.5.4"
serde = "1.0.102"
serde_derive = "1.0.102"
chrono = { version = "0.4.9", features = ["serde"] }
slug = "0.1.4"
