[package]
name = "emile"
version = "0.3.0"
authors = ["Geobert Quach <geobert@protonmail.com>"]
edition = "2021"

[badges]
azure-devops = { project = "geobert/emile", pipeline = "emile-CI", build = "2" }

[dependencies]
anyhow = "1.0.64"
toml = "0.5.9"
serde = "1.0.144"
serde_derive = "1.0.144"
slug = "0.1.4"
notify = { version = "5.0.0", default-features = false, features = ["crossbeam-channel"] }
clap = { version = "3.2.20", features = ["derive"] }
time = { version = "0.3.14", features = ["serde", "formatting", "parsing"] }

