[package]
name = "emile"
version = "0.3.5"
authors = ["Geobert Quach <geobert@protonmail.com>"]
edition = "2021"

[badges]
azure-devops = { project = "geobert/emile", pipeline = "emile-CI", build = "2" }

[dependencies]
anyhow = "1.0.65"
toml = "0.5.9"
serde = "1.0.145"
serde_derive = "1.0.145"
slug = "0.1.4"
notify = { version = "5.0.0", default-features = false }
clap = { version = "4.0.17", features = ["derive"] }
time = { version = "0.3.15", features = ["formatting", "parsing", "macros"] }
tracing = "0.1.37"
lazy_static = "1.4.0"
tokio = { version = "1.21.2", features = ["sync", "macros", "rt-multi-thread", "time"] }
notify-debouncer-mini = { version = "0.2.1", default-features = false }

[dependencies.tracing-subscriber] 
version = "0.3.16"
default-features = false
features = ["std", "env-filter", "fmt", "smallvec", "parking_lot", "registry", "time"]

